version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deer-flow-backend
    environment:
      # Railway 会自动注入这些环境变量
      - LANGGRAPH_CHECKPOINT_SAVER=${LANGGRAPH_CHECKPOINT_SAVER}
      - LANGGRAPH_CHECKPOINT_DB_URL=${LANGGRAPH_CHECKPOINT_DB_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - SEARCH_API=${SEARCH_API}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - PORT=${PORT:-8000}
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    restart: unless-stopped
    networks:
      - deer-flow-network

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_BASE_URL=http://backend:${PORT:-8000}
    container_name: deer-flow-frontend
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:${PORT:-8000}
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - deer-flow-network

networks:
  deer-flow-network:
    driver: bridge

